name: Build 3DWEB

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v5

      - name: Install CIA tools
        run: |
          apt update
          apt install -y p7zip-full curl

          curl -L https://github.com/Epicpkmn11/bannertool/releases/latest/download/bannertool.zip -o bannertool.zip
          7z e bannertool.zip linux-x86_64/bannertool
          chmod +x bannertool
          mv bannertool /usr/local/bin

          curl -L https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.17/makerom-v0.17-ubuntu_x86_64.zip -o makerom.zip
          7z e makerom.zip
          chmod +x makerom
          mv makerom /usr/local/bin

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: 3DWEB-build
          path: |
            **/*.cia
            **/*.3dsx
            **/*.3ds
            **/*.elf
